name: "Deploy to AWS"

# Trigger the workflow from the GitHub UI
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # Specify the Python version you need

      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Install Node.js and npm"
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Specify the Node.js version you need

      - name: "Install pm2 globally"
        run: |
          npm install -g pm2

      - name: "Install Python dependencies"
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: "Deploy to AWS"
        run: |
          source venv/bin/activate
          pm2 restart flask_app # Replace 'flask_app' with the name of your PM2 process
